export const FETCH_VIDEOGAMES_REQUEST = 'FETCH_VIDEOGAMES_REQUEST';
export const FETCH_VIDEOGAMES_SUCCESS = 'FETCH_VIDEOGAMES_SUCCESS';
export const FETCH_VIDEOGAMES_ERROR = 'FETCH_VIDEOGAMES_ERROR';
export const FETCH_VIDEOGAME_DETAIL_REQUEST = 'FETCH_VIDEOGAME_DETAIL_REQUEST';
export const FETCH_VIDEOGAME_DETAIL_SUCCESS = 'FETCH_VIDEOGAME_DETAIL_SUCCESS';
export const FETCH_VIDEOGAME_DETAIL_ERROR = 'FETCH_VIDEOGAME_DETAIL_ERROR';
export const FETCH_VIDEOGAME_BY_NAME = 'FETCH_VIDEOGAME_BY_NAME';
