export const API_KEY = 'b593af6d43b74fd0a63787e262b5bb54';

export const FETCH_PLATFORMS_REQUEST = 'FETCH_PLATFORMS_REQUEST';
export const FETCH_PLATFORMS_SUCCESS = 'FETCH_PLATFORMS_SUCCESS';
export const FETCH_PLATFORMS_ERROR = 'FETCH_PLATFORMS_ERROR';
