export const API_KEY = 'b593af6d43b74fd0a63787e262b5bb54';

export const FETCH_VIDEOGAMES_REQUEST = 'FETCH_VIDEOGAMES_REQUEST';
export const FETCH_VIDEOGAMES_SUCCESS = 'FETCH_VIDEOGAMES_SUCCESS';
export const FETCH_VIDEOGAMES_ERROR = 'FETCH_VIDEOGAMES_ERROR';
export const FETCH_VIDEOGAME_DETAIL_REQUEST = 'FETCH_VIDEOGAME_DETAIL_REQUEST';
export const FETCH_VIDEOGAME_DETAIL_SUCCESS = 'FETCH_VIDEOGAME_DETAIL_SUCCESS';
export const FETCH_VIDEOGAME_DETAIL_ERROR = 'FETCH_VIDEOGAME_DETAIL_ERROR';
export const FETCH_VIDEOGAME_SEARCH = 'FETCH_VIDEOGAME_SEARCH';


